### ISSUE TITLE
Error popup on "Create Components"

### ISSUE THREAD

**Issue by AlwarrenSidh** [AlwarrenSidh/ArmAToolbox#1]
When selecting "Create Components", the following error message appears:

```Traceback (most recent call last):
  File "E:\Users\hfrieden\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\ArmaToolbox\operators.py", line 387, in execute
    ArmaTools.createComponents(context)
  File "E:\Users\hfrieden\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\ArmaToolbox\..\ArmaToolbox\ArmaTools.py", line 499, in createComponents
    vgrp = bpy.context.active_object.vertex_groups.new("Component%02d" % componentNr)
TypeError: VertexGroups.new(): required parameter "name" to be a keyword argument!```

**Comment by poikilos** [comment]
You have to change new(something) to new(name=something) for Blender >= 2.8.

**Comment by AlwarrenSidh** [comment]
Yeah, I know. It's fixed internally already, I need to make a new release ASAP.
