### ISSUE TITLE
Export to p3d error

### ISSUE THREAD

**Issue by RipperRabbit** [AlwarrenSidh/ArmAToolbox#15]
Seem to getting this when I exsport a model to p3d
 File "C:\Users\JoshF\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\ArmaToolbox\__init__.py", line 223, in execute
    exportMDL(self, filePtr, self.selectionOnly);

any ideas ?

**Comment by AlwarrenSidh** [comment]
Need more info. This is only the top level of the call stack.

**Comment by AirsoftArmoury1596** [comment]
This might help;
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\ArmaToolbox\panels.py", line 581, in poll
    return context.active_object.active_material!=None and arma.isArmaObject == True
AttributeError: 'ArmaToolboxProperties' object has no attribute 'isArmaObject'

**Comment by AlwarrenSidh** [comment]
Is the active object a mesh object?

**Comment by AirsoftArmoury1596** [comment]
Yes.
its not giving me the same error anymore, instead of attribute 'isArmaObject' its attributes 'applyModifiers' and 'mergeSameLOD'
