### ISSUE TITLE
Error when starting an existing project - Blender 4.0

### ISSUE THREAD

**Issue by CurryKat** [AlwarrenSidh/ArmAToolbox#49]
Hi ! 

Sorry to disturb you, I have a problem when starting an existing project.

`Read prefs: "C:\Users\Yann\AppData\Roaming\Blender Foundation\Blender\4.0\config\userpref.blend"
Traceback (most recent call last):
  File "E:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "E:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Yann\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\TexTools_1_5\__init__.py", line 128, in <module>
    from . import op_texel_density_set
  File "C:\Users\Yann\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\TexTools_1_5\op_texel_density_set.py", line 3, in <module>
    from bpy.types import FaceMap
ImportError: cannot import name 'FaceMap' from 'bpy.types' (unknown location)
ArmaToolbox registering
Internal classes...
properties
registering properties
operators
menus
panels
lists
BatchMDLExport register
Register done
Traceback (most recent call last):
  File "E:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "E:\Program Files (x86)\Steam\steamapps\common\Blender\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Yann\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\TexTools_1_5\__init__.py", line 128, in <module>
    from . import op_texel_density_set
  File "C:\Users\Yann\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\TexTools_1_5\op_texel_density_set.py", line 3, in <module>
    from bpy.types import FaceMap
ImportError: cannot import name 'FaceMap' from 'bpy.types' (unknown location)
Read blend: "D:\D├®veloppement 3D\.work\A3PL\A3PL_TourRadio\.dev\untitled.blend"
Load Hook: D:\Développement 3D\.work\A3PL\A3PL_TourRadio\.dev\untitled.blend`

Blender is working properly but if I close the console window opened, Blender just closes.

I don't have this error when starting a new project from scratch. I hope no one asked before me for this problem. I didn't find any question close to my one, so...

I tried to uninstall and install again, closing Blender between, checking if the folder was properly removed from my Roaming but the error is still coming.

Thanks for the help you'll offer !

**Comment by AlwarrenSidh** [comment]
This isn't a Toolbox error. The import errors are from TexTools, you might need to update that to a newer version.
