### ISSUE TITLE
Mesh Normals can't be Calculated

### ISSUE THREAD

**Issue by SigmaEOD** [AlwarrenSidh/ArmAToolbox#57]
Having an issue while exporting my model to P3D

I've installed the latest 4.1 version of blender and the latest release of A3 Blender Tools

Here is my error log:

`Python: Traceback (most recent call last):
  File "C:\Users\alexa\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ArmaToolbox\..\ArmaToolbox\MDLexporter.py", line 944, in execute
    #try:
  File "C:\Users\alexa\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ArmaToolbox\..\ArmaToolbox\MDLexporter.py", line 713, in exportMDL
    if len(objects) == 0:
  File "C:\Users\alexa\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ArmaToolbox\..\ArmaToolbox\MDLexporter.py", line 811, in exportObjectListAsMDL
    newTmpObj.select_set(True)
  File "C:\Users\alexa\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ArmaToolbox\..\ArmaToolbox\MDLexporter.py", line 677, in exportLodLevelWithModifiers
    possiblyRenumberComponents(tmpObj)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ArmaToolbox\..\ArmaToolbox\MDLexporter.py", line 499, in export_lod
    #normalOffsetInFile = filePtr.tell();
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexa\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ArmaToolbox\..\ArmaToolbox\MDLexporter.py", line 153, in writeNormals
    if (4,1,0) > bpy.app.version:
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'calc_normals_split'
`

**Comment by AlwarrenSidh** [comment]
Try to delete the addon and re-install it. The later toolbox does not call calc_normal_split anymore if the version is greater than 4.0.
