### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Forskorned** [AlwarrenSidh/ArmAToolbox#58]
Traceback (most recent call last):
  File "D:\SteamLibrary\steamapps\common\Blender\4.1\scripts\modules\addon_utils.py", line 444, in enable
    mod.register()
  File "C:\Users\Fenoj\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ArmaToolbox\__init__.py", line 2334, in register
    bpy.utils.register_module(__name__, verbose=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'bpy.utils' has no attribute 'register_module'

If anyone could help with this it would be greatly appreciated. I keep getting this error anytime after I install the newest version of Arma Toolbox onto my blender and then checking the enabled box.

**Comment by AlwarrenSidh** [comment]
There is something seriously wrong if bpy.utils doesn't have register_module. I'd recomment a reinstall of both blender and the Toolbox
