### ISSUE TITLE
RuntimeError: Model X contains n-gons and cannot be exported

### ISSUE THREAD

**Issue by MultiTheFranky** [AlwarrenSidh/ArmAToolbox#6]
`Write lod  0
Writing Vertices
Writing Normals
Writing faces
taggs: Named selections
taggs: sharp edges
taggs: mass (if any)
taggs: named props
taggs: uvsets
Write lod  1
Writing Vertices
Writing Normals
Writing faces
taggs: Named selections
taggs: sharp edges
taggs: mass (if any)
taggs: named props
taggs: uvsets
Write lod  2
Writing Vertices
Writing Normals
Writing faces
taggs: Named selections
taggs: sharp edges
taggs: mass (if any)
taggs: named props
taggs: uvsets
Write lod  3
Writing Vertices
Writing Normals
Writing faces
taggs: Named selections
taggs: sharp edges
taggs: mass (if any)
taggs: named props
taggs: uvsets
Write lod  4
Writing Vertices
Writing Normals
Writing faces
taggs: Named selections
taggs: sharp edges
taggs: mass (if any)
taggs: named props
taggs: uvsets
Write lod  5
Writing Vertices
Writing Normals
Writing faces
Traceback (most recent call last):
  File "C:\Users\franc\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\ArmaToolbox\__init__.py", line 223, in execute
    exportMDL(filePtr, self.selectionOnly);
  File "C:\Users\franc\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\ArmaToolbox\..\ArmaToolbox\MDLexporter.py", line 411, in exportMDL
    export_lod(filePtr, obj, wm, idx)
  File "C:\Users\franc\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\ArmaToolbox\..\ArmaToolbox\MDLexporter.py", line 327, in export_lod
    writeFaces(filePtr, obj, mesh)
  File "C:\Users\franc\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\ArmaToolbox\..\ArmaToolbox\MDLexporter.py", line 110, in writeFaces
    raise RuntimeError("Model " + obj.name + " contains n-gons and cannot be exported")
RuntimeError: Model Geometry PhysX contains n-gons and cannot be exported`
I don't know if this is a normal behaviour, but in 2.79 I don't have that problem

**Comment by RacerXx** [comment]
ive seen that error before. in 2.79 and 2.8X triangulate all faces of the model should fix this error

**Comment by AlwarrenSidh** [comment]
The above. 2.79 could automatically triangulate n-gons and only ngons, but 2.80 doesn't do that anymore. So far I have not found a way to do this in a plausible way automatically.
