### ISSUE TITLE
Cant install on blender 4.1, 4.2.0, 4.23

### ISSUE THREAD

**Issue by tecj** [AlwarrenSidh/ArmAToolbox#62]
Version of addon latest, armatoolbox-4.2.0.zip, downloaded from here.
All versoions of blender clean and downloaded from 
[https://download.blender.org/release/](url)
Console log: 

`Traceback (most recent call last):
  File "Y:\_progarms\blender-4.2.0-windows-x64\4.2\scripts\modules\addon_utils.py", line 401, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Y:\_progarms\blender-4.2.0-windows-x64\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\ArmaToolbox\__init__.py", line 24, in <module>
    from MDLImporter import importMDL
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\ArmaToolbox\..\ArmaToolbox\MDLImporter.py", line 13, in <module>
    import ArmaToolbox
ModuleNotFoundError: No module named 'ArmaToolbox'
Error: No module named 'ArmaToolbox'
reloading addon meta-data: bl_ext.user_default.ArmaToolbox 'C:\\Users\\Administrator\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\extensions\\user_default\\ArmaToolbox\\blender_manifest.toml' (time-stamp change detected)
Traceback (most recent call last):
  File "Y:\_progarms\blender-4.2.0-windows-x64\4.2\scripts\modules\addon_utils.py", line 401, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Y:\_progarms\blender-4.2.0-windows-x64\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\ArmaToolbox\__init__.py", line 24, in <module>
    from MDLImporter import importMDL
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\ArmaToolbox\..\ArmaToolbox\MDLImporter.py", line 13, in <module>
    import ArmaToolbox
ModuleNotFoundError: No module named 'ArmaToolbox'
`

**Comment by tecj** [comment]
Just was able to install addon on blender ver 4.1.1 by manualy coppy all folder ArmaToolbox in blender-4.1.1-windows-x64\4.1\scripts\addons\, after restart blender addon showing in list of addons and I can eneble it.
On blender versions 4.2-3, cant repeat this, still doesnt work and show error no module name

**Comment by tecj** [comment]
By adding addon by blender module installer in zip file not working on all versions.

**Comment by Shan3Walsh** [comment]
> Just was able to install addon on blender ver 4.1.1 by manualy coppy whole unzipped folder ArmaToolbox in blender-4.1.1-windows-x64\4.1\scripts\addons, after restart blender addon showing in list of addons and I can enable it. On blender versions 4.2-3, cant repeat this, still doesnt work and show error no module name

Happening with me as well

**Comment by AlwarrenSidh** [comment]
Make sure you do not just download a ZIP from the repository, you must use the one provided in the release.

**Comment by Shan3Walsh** [comment]
Right thats what I did. I used the zip file provided in the repository on the newest version of blender. I will try it again just to be sure and will reply back with my results.

**Comment by Shan3Walsh** [comment]
Attached are screen shots of my results doing the exact thing above still getting the "No Module named ArmaToolBox" error. I tried clearing out the install manually also and reinstalled it using 4.2.3 LTS. Any ideas of what I can do next to get this working?

![Screenshot 2024-11-04 034734](https://github.com/user-attachments/assets/accdb1c6-4331-468b-85ce-1f2a5aee0e47)
![Screenshot 2024-11-04 034803](https://github.com/user-attachments/assets/83402211-dbde-4a2e-aa52-57ba1902eff5)
![Screenshot 2024-11-04 034847](https://github.com/user-attachments/assets/ce396032-ad9d-46bd-b14e-98ce12ba2754)

**Comment by AlwarrenSidh** [comment]
You downloaded the wrong (source) archive. There is no README.md in the distribution archive.
